spring.application.name=echoscan

spring.datasource.url=jdbc:postgresql://localhost:5432/echoscan
spring.datasource.username=postgres
spring.datasource.password=2002

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs