spring.application.name=car-api
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=car-api
spring.datasource.username=postgres
spring.datasource.password=2002
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#SECUR?TY
spring.security.user.name=${NAME}
spring.security.user.password=${SIFRE}
