spring.application.name=realitygraph
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=realitygraph
spring.datasource.username=postgres
spring.datasource.password=2002
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.google.genai.api-key=AIzaSyDyWEn_b9cyzQjqCCH1xvMIRLX8mGdZFBU
spring.ai.google.genai.project-id=1034632100573
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
